apiVersion: v1
kind: Service
metadata:
  name: blunderlist-gateway
  labels:
    app.kubernetes.io/name: blunderlist-gateway
    app.kubernetes.io/instance: blunderlist-gateway
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: blunderlist
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: gateway
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: blunderlist-gateway
    app.kubernetes.io/instance: blunderlist-gateway
    serving: "true"
